filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/main-application/*.log
      - /logs/tcp-provider/*.log
      - /logs/rest-provider/*.log
      - /logs/kafka-consumer/*.log
      - /logs/kafka-consumer-opensearch/*.log
    fields:
      application: financial-simple-rates
    fields_under_root: true
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2}'
      negate: true
      match: after

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

setup.template.name: "financial-simple-rates-logs"
setup.template.pattern: "financial-simple-rates-logs-*"
setup.ilm.enabled: false
setup.template.enabled: true
output.elasticsearch:

  hosts: ["opensearch:9200"]
  protocol: "http"
  username: ""
  password: ""
  index: "financial-simple-rates-logs-%{+yyyy.MM.dd}"
  setup.template.enabled: false
  setup.ilm.enabled: false

logging.level: info