server:
  port: 8080

spring:
  application:
    name: rest-rate-provider
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

# Security Configuration - Authentication credentials
app:
  security:
    username: ${APP_SECURITY_USERNAME:defaultuser}
    password: ${APP_SECURITY_PASSWORD:defaultpass}

logging:
  level:
    root: INFO
    com.toyota: INFO
    org.springframework.security: DEBUG
    org.springframework.security.authentication: DEBUG

rate:
  simulation:
    volatility: ${RATE_SIMULATION_VOLATILITY:0.001}
    minSpread: ${RATE_SIMULATION_MIN_SPREAD:0.0001}
    maxRetries: ${RATE_SIMULATION_MAX_RETRIES:10}
