# Application settings
spring:
  application:
    name: kafka-consumer-opensearch
  
  # Kafka consumer configuration
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false

  # OpenSearch Configuration
  elasticsearch:
    uris: ${OPENSEARCH_URIS:http://opensearch:9200}
    username: ${OPENSEARCH_USERNAME:}
    password: ${OPENSEARCH_PASSWORD:}
    connection-timeout: 5s
    socket-timeout: 5s

# Server Configuration
server:
  port: 8086

# Logging Configuration
logging:
  level:
    root: INFO
    com.toyota: DEBUG
    org.springframework.data.elasticsearch: INFO
    org.springframework.kafka: INFO

# Application specific Kafka configuration
app:
  kafka:
    consumer:
      group-id: opensearch-consumer-group
    topic:
      simple-rates: financial-simple-rates
      json-rates: financial-rates-json
  
  # OpenSearch index adı
  opensearch:
    index-name: financial_rates_logs